### ISSUE TITLE
Uso do projeto.

### ISSUE THREAD

**Issue by otavio-s-s** [gabriel19913/soccer_probability#1]
Fala Gabriel, tudo bem? 

Acabei de ler seu tutorial sobre previsão da pontuação do campeonato brasileiro no DataHackers e achei incrível, parabéns!

Estou começando a desenvolver algo parecido, construindo um banco de dados com dados sobre todas as partidas da Premier League na atual temporada (depois pretendo expandir para as demais). Até o momento, fiz web scraping de dados partida a partida diretamente do site da premier league. Tenho dados de gols, cartões, posse de bola, passes, finalizações, escalações, etc de cada time, partida a partida. Você pode ver [aqui](https://github.com/otavio-s-s/data_science/tree/master/Premier%20League%20Scraping). 

Agora pretendo acrescentar a cada jogo informações da tabela antes de cada rodada, como posição, número de gols, etc. Já estava prestes a começar a tentar gerar essas tabelas partir dos dados das partidas individuais, o que imagino que seja um trabalho descomunal, quando encontrei a segunda parte do seu tutorial, que faz exatamente o que eu preciso. 

Então estou te escrevendo para saber se há algum problema em usar seu código para esse fim e, claro, se você tiver interesse em contribuir, será bem-vindo.  Forte abraço!

**Comment by gabriel19913** [comment]
Olá Otávio tudo bem? Não tem problema algum de usar o código. 
Só gostaria de pedir que você desse os créditos se for divulgar em algum lugar :)

E se precisar de ajuda com algo e tiver alguma dúvida pode me falar. 
Posso contribuir com o que precisar, apenas ando meio ocupado. 
Mas se precisar de algo pode falar!
